# Generated by Django 5.1.7 on 2025-05-02 19:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kabupaten',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nm_kabupaten', models.CharField(max_length=100)),
                ('kode', models.CharField(blank=True, max_length=10, null=True)),
                ('is_kota', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Kabupaten',
                'db_table': 'kabupaten',
                'ordering': ['provinsi', 'nm_kabupaten'],
            },
        ),
        migrations.CreateModel(
            name='KategoriProduk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nm_kategori', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Kategori Produk',
                'db_table': 'kategori_produk',
                'ordering': ['nm_kategori'],
            },
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nm_provinsi', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Provinsi',
                'db_table': 'provinsi',
                'ordering': ['nm_provinsi'],
            },
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nm_kecamatan', models.CharField(max_length=100)),
                ('kode', models.CharField(blank=True, max_length=10, null=True)),
                ('kabupaten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kecamatan', to='crud.kabupaten')),
            ],
            options={
                'verbose_name_plural': 'Kecamatan',
                'db_table': 'kecamatan',
                'ordering': ['kabupaten', 'nm_kecamatan'],
            },
        ),
        migrations.CreateModel(
            name='LokasiPenjualan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nm_lokasi', models.CharField(max_length=255)),
                ('tipe_lokasi', models.CharField(max_length=20)),
                ('alamat', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('tlp_pengelola', models.CharField(blank=True, max_length=20, null=True)),
                ('kecamatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lokasi_penjualan', to='crud.kecamatan')),
            ],
            options={
                'verbose_name_plural': 'Lokasi Penjualan',
                'db_table': 'lokasi_penjualan',
                'ordering': ['nm_lokasi'],
            },
        ),
        migrations.CreateModel(
            name='LokasiUMKM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('alamat_lengkap', models.TextField()),
                ('kode_pos', models.CharField(blank=True, max_length=10, null=True)),
                ('tgl_update', models.DateTimeField(auto_now=True)),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lokasi_umkm', to='crud.kecamatan')),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lokasi_umkm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lokasi UMKM',
                'db_table': 'lokasi_umkm',
                'ordering': ['pengguna'],
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nm_produk', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('stok', models.PositiveIntegerField(default=0)),
                ('satuan', models.CharField(max_length=50)),
                ('bahan_baku', models.TextField(blank=True, null=True)),
                ('metode_produksi', models.TextField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('tgl_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tgl_update', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produk', to='crud.kategoriproduk')),
                ('umkm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produk', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Produk',
                'db_table': 'produk',
                'ordering': ['nm_produk'],
            },
        ),
        migrations.CreateModel(
            name='ProdukTerjual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tgl_penjualan', models.DateField()),
                ('jumlah_terjual', models.PositiveIntegerField()),
                ('harga_jual', models.IntegerField()),
                ('total_penjualan', models.IntegerField()),
                ('catatan', models.TextField(blank=True, null=True)),
                ('tgl_pelaporan', models.DateTimeField(auto_now_add=True)),
                ('lokasi_penjualan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penjualan', to='crud.lokasipenjualan')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penjualan', to='crud.produk')),
            ],
            options={
                'verbose_name_plural': 'Produk Terjual',
                'db_table': 'produk_terjual',
                'ordering': ['tgl_penjualan'],
            },
        ),
        migrations.CreateModel(
            name='ProfilUMKM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nm_bisnis', models.CharField(blank=True, max_length=255, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('tlp', models.CharField(blank=True, max_length=20, null=True)),
                ('desc_bisnis', models.TextField(blank=True, null=True)),
                ('tgl_bergabung', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_umkm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profil UMKM',
                'db_table': 'profil_umkm',
                'ordering': ['user', 'nm_bisnis'],
            },
        ),
        migrations.AddField(
            model_name='kabupaten',
            name='provinsi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kabupaten', to='crud.provinsi'),
        ),
    ]
