# Generated by Django 5.1.7 on 2025-05-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkterjual',
            name='harga_jual',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produkterjual',
            name='total_penjualan',
            field=models.IntegerField(),
        ),
    ]
